[actuation]
t_on = 100
t_off = 80
t_full = 230
curve = "linear"
gamma = 2.0

[thumb]
up = "UP"
down = "DOWN"
left = "LEFT"
right = "RIGHT"
button = "F24"
button_switches_layer = true
wheel_up = "VOLUME_UP"
wheel_down = "VOLUME_DOWN"

[analog]
keys = [
  { mode = "key", bind = "1" },
  { mode = "key", bind = "2" },
  { mode = "key", bind = "3" },
  { mode = "key", bind = "4" },
  { mode = "key", bind = "5" },
  { mode = "key", bind = "6" },
  { mode = "key", bind = "7" },
  { mode = "key", bind = "8" },
  { mode = "key", bind = "9" },
  { mode = "key", bind = "0" },
  { mode = "key", bind = "A" },
  { mode = "key", bind = "B" },
  { mode = "key", bind = "C" },
  { mode = "key", bind = "D" },
  { mode = "key", bind = "E" },
  { mode = "key", bind = "F" },
  { mode = "key", bind = "G" },
  { mode = "key", bind = "H" },
  { mode = "key", bind = "I" },
  { mode = "key", bind = "J" },
]
layer1 = [
  { mode = "key", bind = "F1" },
  { mode = "key", bind = "F2" },
  { mode = "key", bind = "F3" },
  { mode = "key", bind = "F4" },
  { mode = "key", bind = "F5" },
  { mode = "key", bind = "F6" },
  { mode = "key", bind = "F7" },
  { mode = "key", bind = "F8" },
  { mode = "key", bind = "F9" },
  { mode = "key", bind = "F10" },
  { mode = "key", bind = "F11" },
  { mode = "key", bind = "F12" },
  { mode = "key", bind = "HOME" },
  { mode = "key", bind = "END" },
  { mode = "key", bind = "PAGEUP" },
  { mode = "key", bind = "PAGEDOWN" },
  { mode = "key", bind = "INSERT" },
  { mode = "key", bind = "DELETE" },
  { mode = "key", bind = "UP" },
  { mode = "key", bind = "DOWN" },
]
